main: main.o personne.o
	gcc -o main main.o personne.o

main.o: main.c
	gcc -c main.c

biblio.o: biblio.c
	gcc -c biblio.c

complex.o: complex.c
	gcc -c complex.c
personne.o: personne.c
	gcc -c personne.c
