main : main.o  TrajetSimple.o Cell.o Linkedlist.o TrajetCompose.o Catalogue.o Trajet.o
	g++ -g  -o main main.o  TrajetSimple.o Cell.o Linkedlist.o TrajetCompose.o Catalogue.o Trajet.o

main.o : main.cpp
	g++ -c main.cpp

Catalogue.o: Catalogue.cpp
	g++ -c Catalogue.cpp

TrajetSimple.o : TrajetSimple.cpp
	g++ -c TrajetSimple.cpp

Cell.o: Cell.cpp
	g++ -c Cell.cpp

Linkedlist.o: Linkedlist.cpp
	g++ -c Linkedlist.cpp

TrajetCompose.o: TrajetCompose.cpp
	g++ -c TrajetCompose.cpp

Trajet.o: Trajet.cpp
	g++ -c Trajet.cpp